#!/usr/bin/env bash
# Stand up a local, throwaway FinOps demo: a local Supabase stack with a
# the owner-free schema + synthetic data. Production data is never touched.
#
# The stack runs from an ISOLATED project dir (~/.finops-demo) on REMAPPED ports
# (543xx -> 544xx) so it (a) never mutates this git checkout — safe while other
# sessions commit here — and (b) coexists with any other local Supabase stack you
# already have running on the default ports.
#
# Usage:  scripts/demo/up.sh
# Then:   set -a; source .env.demo.local; set +a; npm run dev   (or pnpm dev)
set -euo pipefail

cd "$(dirname "$0")/../.."
ROOT="$PWD"
DEMO_DIR="${FINOPS_DEMO_DIR:-$HOME/.finops-demo}"

command -v supabase >/dev/null || { echo "supabase CLI not found"; exit 1; }
docker info >/dev/null 2>&1 || { echo "Docker is not running — start Docker Desktop first."; exit 1; }

# @supabase/supabase-js needs native WebSocket (Node >= 22). Resolve one.
NODE="node"
if ! "$NODE" -e 'process.exit(+process.versions.node.split(".")[0]>=22?0:1)' 2>/dev/null; then
  for cand in "$HOME"/.nvm/versions/node/v2[23]*/bin/node; do
    [ -x "$cand" ] && NODE="$cand" && break
  done
fi
"$NODE" -e 'if(+process.versions.node.split(".")[0]<22){console.error("Need Node >=22 (found "+process.version+"). Install it (e.g. nvm install 22) and re-run.");process.exit(1)}' || exit 1

echo "▶  preparing isolated demo project at $DEMO_DIR"
mkdir -p "$DEMO_DIR/supabase"

# Isolated config: distinct project_id + every 5432x port shifted to 5442x +
# auth redirect/site_url aligned to localhost:3000 so the magic-link login works.
sed -e 's/^project_id = .*/project_id = "finops-demo"/' \
    -e 's/543\([0-9][0-9]\)/544\1/g' \
    -e 's#^site_url = .*#site_url = "http://localhost:3000"#' \
    -e 's#^additional_redirect_urls = .*#additional_redirect_urls = ["http://localhost:3000/auth/callback", "http://localhost:3000", "http://127.0.0.1:3000/auth/callback"]#' \
    "$ROOT/supabase/config.toml" > "$DEMO_DIR/supabase/config.toml"

# the owner-free migration set (built fresh from the real migrations, read-only).
"$NODE" "$ROOT/scripts/demo/build_schema.mjs" \
  --src "$ROOT/supabase/migrations" --out "$DEMO_DIR/supabase/migrations"

cd "$DEMO_DIR"
echo "▶  starting local Supabase (first run pulls images, can take a few minutes)…"
supabase start
echo "▶  applying demo schema…"
supabase db reset

echo "▶  writing $ROOT/.env.demo.local"
STATUS="$(supabase status -o env)"
api_url=$(echo "$STATUS"  | sed -n 's/^API_URL="\{0,1\}\([^"]*\)"\{0,1\}$/\1/p')
anon=$(echo "$STATUS"     | sed -n 's/^ANON_KEY="\{0,1\}\([^"]*\)"\{0,1\}$/\1/p')
service=$(echo "$STATUS"  | sed -n 's/^SERVICE_ROLE_KEY="\{0,1\}\([^"]*\)"\{0,1\}$/\1/p')
mail_url=$(echo "$STATUS" | sed -n 's/^\(MAILPIT_URL\|INBUCKET_URL\)="\{0,1\}\([^"]*\)"\{0,1\}$/\2/p' | head -1)
: "${api_url:?could not parse API_URL from supabase status}"

cat > "$ROOT/.env.demo.local" <<EOF
# Local demo stack — generated by scripts/demo/up.sh. Gitignored, throwaway.
NEXT_PUBLIC_SUPABASE_URL=$api_url
NEXT_PUBLIC_SUPABASE_ANON_KEY=$anon
SUPABASE_SERVICE_ROLE_KEY=$service
NEXT_PUBLIC_APP_URL=http://localhost:3000
DEFAULT_CURRENCY=NZD
DEMO_EMAIL=${DEMO_EMAIL:-demo@finops.local}
DEMO_PASSWORD=${DEMO_PASSWORD:-demo-finops-123}
EOF

echo "▶  seeding synthetic data…"
set -a; source "$ROOT/.env.demo.local"; set +a
"$NODE" "$ROOT/scripts/demo/seed_demo.mjs"

cat <<EOF

✅ Demo stack ready (isolated project 'finops-demo', API at $api_url).
   Run the app against it:
     set -a; source .env.demo.local; set +a
     npm run dev        # or: pnpm dev
   Open http://localhost:3000 and log in as ${DEMO_EMAIL:-demo@finops.local}.
   The magic-link email lands in the local mail catcher: ${mail_url:-see 'supabase status'}

   Tear down later:  (cd "$DEMO_DIR" && supabase stop)
EOF
